title: radioegor146's blog
lang: "en"
permalink: /:title/
excerpt_separator: "\n\n\n"
date_format: "%d.%m.%Y"
email: radioegor146@ctf.by
description: >- 
  Just a random blog from random author. Reverse engineering, crazy engineering and so on!
baseurl: ""
domain: "b.re146.dev"
url: "https://b.re146.dev"
github_username:  radioegor146
remote_theme: niklasbuschmann/contrast
show_excerpts: true         
show_frame: true        
navigation:                   
  - {file: "archive.html", sidebaricon: home}
  - {file: "about.markdown", sidebaricon: address-card}

external:                     
  - {title: Website, icon: globe, url: "https://re146.dev"}

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap